### ISSUE TITLE
大佬，关于您写的博客添加搜索功能，有些疑问想请教

### ISSUE THREAD

**Issue by Chow-Ray** [liucent/Blog#1]
https://www.ariesme.com/posts/2019/add_google_custom_search_for_hugo/
我与您用是是同款主题toha，请问您教程中所写的代码，都是添加在什么地方？我配置到配置文件中，没有反应。我看了您博客的配置文件，也没有找到相关代码，能麻烦您解答下吗？

**Comment by liucent** [comment]
您好，不好意，这个教程是很早以前用另外一个主题时用的gcs。toha主题中的搜索功能我是用的lunr.js，搜索时调用Blog/static/assets/js/search.js，站点文章的数据集在Blog/docs/posts/index.json。Blog/layouts/_default/list.json这个文件是生成搜索数据集的模板。然后只要在站点配置文件里添加outputs: section: ["html", "json"]参数，生成站点时就会同时生成站点文章的json数据集了。
